# Generated by Django 6.0.1

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_shippingzone_alter_wishlist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(folder='products', max_length=255, verbose_name='product_image'),
        ),
    ]
