# Generated by Django 6.0.1 on 2026-05-11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_category_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('CREATED', 'Créé'), ('UPDATED', 'Mis à jour'), ('DELETED', 'Supprimé'), ('STATUS_CHANGED', 'Changement de statut'), ('OTHER', 'Autre')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal d\u2019audit produit',
                'verbose_name_plural': 'Journaux d\u2019audit produits',
                'ordering': ['-created_at'],
            },
        ),
    ]

