# Generated by Django 6.0.1 on 2026-05-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_product_auditlog'),
        # StockMovement référence Order (apps.orders) → on dépend de la dernière migration orders
        ('orders', '0005_order_payment_url_alter_order_paygate_tx_id_and_more'),
    ]

    operations = [
        # --- Ajout des champs stock manquants sur Product (aucune perte de données) ---
        migrations.AddField(
            model_name='product',
            name='restocking_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de réapprovisionnement estimée'),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, verbose_name="Seuil d'alerte stock faible"),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_alert_sent',
            field=models.BooleanField(default=False, verbose_name='Alerte stock faible envoyée'),
        ),
        # --- Création des tables de gestion des stocks ---
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantité')),
                ('movement_type', models.CharField(choices=[('SUPPLY', 'Approvisionnement'), ('SALE', 'Vente'), ('CANCEL', 'Annulation'), ('REFUND', 'Remboursement'), ('MANUAL', 'Correction manuelle'), ('INVENTORY', 'Inventaire')], max_length=20, verbose_name='Type de mouvement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='products.product')),
            ],
            options={
                'verbose_name': 'Réservation de stock',
                'verbose_name_plural': 'Réservations de stock',
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('notification_type', models.CharField(default='low_stock', max_length=50, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Notification Admin',
                'verbose_name_plural': 'Notifications Admin',
                'ordering': ['-created_at'],
            },
        ),
    ]
