# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_stock_features'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='product_stock_non_negative'),
        ),
    ]
