# Generated by Django 6.0.4 on 2026-08-11 12:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_product_stock_non_negative'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Note moyenne'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre total d'avis"),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Nom affiché publiquement', max_length=150, verbose_name='Nom ou Pseudonyme')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name="Titre de l'avis")),
                ('comment', models.TextField(verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(db_index=True, default=False, verbose_name='Approuvé / Public')),
                ('is_pinned', models.BooleanField(default=False, help_text='Afficher en priorité', verbose_name='Épinglé')),
                ('is_featured', models.BooleanField(default=False, verbose_name="Mis en avant sur l'accueil")),
                ('verified_purchase', models.BooleanField(default=False, verbose_name='Achat vérifié')),
                ('admin_reply', models.TextField(blank=True, verbose_name="Réponse de l'administrateur")),
                ('admin_reply_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='Produit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Avis client',
                'verbose_name_plural': 'Avis clients',
                'ordering': ['-is_pinned', '-created_at'],
                'unique_together': {('product', 'user')},
            },
        ),
    ]
