# Generated by Django 6.0.1 on 2026-03-11 20:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='banner_image'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='favicon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
    ]
