# Generated by Django 6.0.4 on 2026-08-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_banner_image_alter_sitesettings_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='reviews_homepage_enabled',
            field=models.BooleanField(default=True, verbose_name="Activer les avis sur l'accueil"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='reviews_homepage_limit',
            field=models.PositiveIntegerField(default=6, verbose_name="Nombre d'avis max sur l'accueil"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='reviews_homepage_mode',
            field=models.CharField(choices=[('recent', 'Les plus récents'), ('best', 'Les mieux notés (4+ étoiles)'), ('pinned', 'Uniquement les avis épinglés'), ('mix', 'Mélange (Épinglés puis Récents/Mieux notés)')], default='mix', max_length=20, verbose_name="Mode d'affichage accueil"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='reviews_only_buyers',
            field=models.BooleanField(default=False, verbose_name='Dépôt réservé aux acheteurs vérifiés'),
        ),
    ]
